---
abstract: 'Convert Moose libraries to Mouse ones, or vice versa'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Moose: 0.9
  Mouse: 0.4
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Any::Moose::Convert
name: Any-Moose-Convert
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  PerlIO::Util: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-MooseToMouse.git
version: 0.001
